name: Build & test

on:
  pull_request:
  push:


jobs:
  main:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - run: date > date.txt

    - name: Archive deployment files as artifact
      uses: actions/upload-artifact@v3
      with:
        name: test-deployment-files
        path: |
          date.txt
