name: Build & test

on:
  pull_request:
  push:


jobs:
  main:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - run: date > date.txt
    - run: |
        echo $BANANA
        echo $BANANA | base64
        echo $BANANA | rev
        echo $BANANA | rev | base64
        echo $BANANA | wc -c
      env:
        BANANA: ${{ secrets.PETER }}

    - name: Archive deployment files as artifact
      uses: actions/upload-artifact@v3
      with:
        name: test-deployment-files
        path: |
          date.txt

    - name: Invoke workflow
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: deploy.yml
